# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найменшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (1), (30, 56, 25), (10, 20), (33, ), (40,), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [1]:
def func(l):
    li = list(filter(lambda x: type(x) == tuple, l))
    return l.index(min(li, key=lambda x: sum(x)))
func([(10, 20), (1), (30, 56, 25), (10, 20), (33, ), (40,), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)])

9

### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [2]:
def strToDict(s):
    import re
    from collections import Counter
    words = [x.lower() for x in re.findall(r"[\w']+", s)]
    return dict(Counter(words))
strToDict("Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text.")

{'also': 1,
 'analytics': 1,
 'as': 1,
 'data': 1,
 'deriving': 1,
 'equivalent': 1,
 'from': 1,
 'high': 1,
 'information': 1,
 'is': 1,
 'mining': 2,
 'of': 1,
 'process': 1,
 'quality': 1,
 'referred': 1,
 'roughly': 1,
 'text': 4,
 'the': 1,
 'to': 2}

### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле, N > 0). Кожен наступний день він зменшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50) до тих пір, коли дистанція пробігу за день стала меншою, ніж N / R (R - ціле, 0 < R < N, N / R - дійсне), після цього дня спортсмен збільшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня, до тих пір, коли дистанція за день стала більшою, ніж N**R . Після цього дня виконувалось початкове правило, тобто дистанція зменшувалась до N/R, а потім збільшувалась до N**R за вищеописаним циклічним законом. По заданим Р, N, M, R, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 10хв
```

In [4]:
def count_dist(P, N, M, R):
    sum_d = N
    i = 1
    current = N
    P = P / 100
    flag = True
    while sum_d <= M:
        if flag:
            if current >= N/R:
                current = (1 - P) * current
            else:
                flag = False
        if not flag:
            if current <= N * R:
                current = (1 + P) * current
            else:
                flag = True
        sum_d += current
        i += 1
    return i, sum_d

print(count_dist(30, 40, 50, 10))

(2, 68.0)


### 4. Реалізуйте клас Torus, який створюється за двома радіусами r, R, R > r. Містить два методи, які повертають відповідно: площу поверхні та об'єм.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 6хв
```

### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 10хв
```

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного стовпчику від кожного елементу у відповідному стовпчику:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [13]:
import numpy as np
A = np.array([[17,24,1,8,15], [23,5,7,14,16], [4,6,13,20,22], [10,12,19,21,3], [11,18,25,2,9]])
res = []
for row in A.T:
    new_row = [int(x - row.mean()) for x in row]
    res.append(new_row)
res = np.array(res).T
print(res)

[[  4  11 -12  -5   2]
 [ 10  -8  -6   1   3]
 [ -9  -7   0   7   9]
 [ -3  -1   6   8 -10]
 [ -2   5  12 -11  -4]]


### 7. Дано наступну матрицю:
\begin{align}
B = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}


#### 7.1. Знайдіть найближче значення в матриці B до будь-якого довільно заданого скаляра.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бал
Рекомендований час: 2хв
```

In [40]:
B = np.array([[1, 24, 1, 8, 15], [-3, 5, 7, -14, 16], [4, 6, -3, 20, 2], [10, 12, 19, 21, 3], [1, 1, 2, -2, 0]])
def dist(B, sc):
    D = np.abs(B - sc)
    min_el = 0, 0
    for i, row in enumerate(D):
        j = np.argmin(row)
        if D[i, j] < D[min_el]:
            min_el = i, j
    return B[min_el]
print(dist(B, 5))

5


#### 7.2. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [42]:
B = np.array([[1, 24, 1, 8, 15], [-3, 5, 7, -14, 16], [4, 6, -3, 20, 2], [10, 12, 19, 21, 3], [1, 1, 2, -2, 0]])
B[(B > 3) & (B < 16)] = 100
print(B)


[[  1  24   1 100 100]
 [ -3 100 100 -14  16]
 [100 100  -3  20   2]
 [100 100  19  21   3]
 [  1   1   2  -2   0]]


### 8. Створіть випадковий вектор розміру 20 і замініть мінімальне за модулем значення на 0
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [51]:
x = np.random.randn(20)
print(x)
x[np.argmin(np.abs(x))] = 0
print(x)

[-0.33290737  0.72967481  0.22967475  0.74736106  1.09352247  0.60851869
 -0.51045481  1.0545666   0.34858336  1.49739653 -0.25081205 -1.22602816
 -0.05614905  0.32594463  1.30133549  0.66314463  0.20848985  1.21141839
  0.04356207  1.3712928 ]
[-0.33290737  0.72967481  0.22967475  0.74736106  1.09352247  0.60851869
 -0.51045481  1.0545666   0.34858336  1.49739653 -0.25081205 -1.22602816
 -0.05614905  0.32594463  1.30133549  0.66314463  0.20848985  1.21141839
  0.          1.3712928 ]


### Pandas

### 9. Розглянемо наступний словник ```data``` та список ```labels```:

In [52]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 9.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [55]:
import pandas as pd
frame = pd.DataFrame(data=data, index=labels)

#### 9.2. Відобразіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [57]:
print(frame)
print(frame.info())

   age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2
f  2.0    cat       no       3
g  4.5  snake       no       1
h  NaN    cat      yes       1
i  7.0    dog       no       2
j  3.0    dog       no       1
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
age         8 non-null float64
animal      10 non-null object
priority    10 non-null object
visits      10 non-null int64
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


#### 9.3. Поверніть перші 5 рядків ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [75]:
frame.head(5)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2

#### 9.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [60]:
frame[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

#### 9.5 Виберіть дані з рядків ```[1, 5, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [68]:
frame.loc[['a', 'e', 'h'], ['animal', 'age']]

animal  age
a    cat  2.5
e    dog  5.0
h    cat  NaN

#### 9.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [73]:
frame.loc[frame['visits'] > 3]

Empty DataFrame
Columns: [age, animal, priority, visits]
Index: []

#### 9.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [83]:
frame.loc[frame['age'].isnull()]

age animal priority  visits
d  NaN    dog      yes       3
h  NaN    cat      yes       1

#### 9.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

#### 9.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 9.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 9.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

## Scipy & Matplotlib

### 10. За допомогою scipy згенерувати та за допомогою matplotlib побудувати вибірки, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 10.1. Виібрку з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 10.2. Вибірку з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 10.3. Вибірку з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 10.4. Вибірку з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```